name: Deploy to Heroku

on:
  push:
    branches: [master]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]
    steps:
      - uses: actions/checkout@v2
      - name: Run tests
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: Copy .env file
        env:
          JWT_SECRET: ${{secrets.JWT_SECRET}}
        run: |
          cd backend && touch .env
          echo JWT_SECRET=${{secrets.JWT_SECRET}} >> .env
          echo MONGO_DB_URL=${{secrets.MONGO_DB_URL}} >> .env
          echo JWT_EXPIRATION=${{secrets.JWT_EXPIRATION}} >> .env
          echo PORT=${{secrets.PORT}} >> .env
          cat .env
      - name: Run install and Tests
        run: |
          cd backend && yarn install
          yarn run dev && sleep 10 && curl http://localhost:6000 && yarn test
          yarn run build
      - name: Set github credentials
        run: |
          ls -l
          git config user.email ${{secrets.USER_EMAIL}}
          git config user.name ${{secrets.USER_NAME}}
  deploy:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v2
      - name: Deploy to dev
        uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_AUTH_TOKEN}}
          heroku_app_name: ${{secrets.HEROKU_APP_NAME}}
          heroku_email: ${{secrets.HEROKU_EMAIL}}